## YAML Template.
---
server:
    port: 9001
    
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
                server:
                    webmvc:         
                        routes:
                        - id: BUKU
                          uri: lb://BUKU
                          predicates: 
                            - Path=api/buku/**
                        - id: ANGGOTA
                          uri: lb://ANGGOTA
                          predicates: 
                            - Path=api/anggota/**
                        - id: PEMINJAMAN
                          uri: lb://PEMINJAMAN
                          predicates: 
                            - Path=api/peminjaman/**
                        - id: PENGEMBALIAN
                          uri: lb://PENGEMBALIAN
                          predicates: 
                            - Path=api/pengembalian/**  
                    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance: 
        hostname: localhost